#ifndef				__MUSIC_CONTROL_H__
#define				__MUSIC_CONTROL_H__

#include "cocos2d.h"
#include "cocos-ext.h"

enum
{
	MUSICCONTROL_EFFECT_ID_CARRY_TARGET,
	MUSICCONTROL_EFFECT_ID_GET_TARGET,
	MUSICCONTROL_EFFECT_ID_BOMB,
	MUSICCONTROL_EFFECT_ID_BUTTON,
	MUSICCONTROL_EFFECT_ID_BUY_FINISH,
	MUSICCONTROL_EFFECT_ID_BUY_FAILED,
	MUSICCONTROL_EFFECT_ID_THROW,
	MUSICCONTROL_EFFECT_ID_PULL,
	MUSICCONTROL_EFFECT_ID_PEAL_OPEN,
	MUSICCONTROL_EFFECT_ID_WIN,
	MUSICCONTROL_EFFECT_ID_FAILED,
	MUSICCONTROL_EFFECT_ID_MONEY_FINISH,// Î´Ìí¼Ó
	MUSICCONTROL_EFFECT_ID_SKILL,
	MUSICCONTROL_EFFECT_ID_PROP,
	MUSICCONTROL_EFFECT_ID_ABSORB,
	MUSICCONTROL_EFFECT_ID_DROP,
	MUSICCONTROL_EFFECT_ID_BALL,
	MUSICCONTROL_EFFECT_ID_SHOP,
	MUSICCONTROL_EFFECT_ID_BUY_THING,
	MUSICCONTROL_EFFECT_ID_BUY_NOTHING,
	MUSICCONTROL_EFFECT_ID_TIME_START,
	MUSICCONTROL_EFFECT_ID_TIME_OUT,
	MUSICCONTROL_EFFECT_ID_TIME_LAST,
	MUSICCONTROL_EFFECT_ID_START_ONE,
	MUSICCONTROL_EFFECT_ID_START_TWO,
	MUSICCONTROL_EFFECT_ID_START_THREE,
	MUSICCONTROL_EFFECT_ID_JINGXIGUI_CARRIED,
	//MUSICCONTROL_EFFECT_ID_JINGXIGUI_BABY,
	//MUSICCONTROL_EFFECT_ID_JINGXIGUI_PET,
	MUSICCONTROL_EFFECT_ID_LINGGANDAWANG_CARRIED,
	//MUSICCONTROL_EFFECT_ID_LINGGANDAWANG_BABY,
	//MUSICCONTROL_EFFECT_ID_LINGGANDAWANG_PET,
	MUSICCONTROL_EFFECT_ID_YUMIANGONGZHU_CARRIED,
	//MUSICCONTROL_EFFECT_ID_YUMIANGONGZHU_BABY,
	//MUSICCONTROL_EFFECT_ID_YUMIANGONGZHU_PET,
	MUSICCONTROL_EFFECT_ID_NIUMOWANG_CARRIED,
	//MUSICCONTROL_EFFECT_ID_NIUMOWANG_BABY,
	//MUSICCONTROL_EFFECT_ID_NIUMOWANG_PET,
	MUSICCONTROL_EFFECT_ID_XIAOCHOUYU_CARRIED,
	MUSICCONTROL_EFFECT_ID_BRID_CARRIED,
	MUSICCONTROL_EFFECT_ID_BAT_CARRIED,
	MUSICCONTROL_EFFECT_ID_STAR_CARRIED,
	MUSICCONTROL_EFFECT_ID_PET_GROW,
	MUSICCONTROL_EFFECT_ID_SHAHESHANG_LINE,
	//MUSICCONTROL_EFFECT_ID_CARTOON_1_1,
	//MUSICCONTROL_EFFECT_ID_CARTOON_1_2,
	//MUSICCONTROL_EFFECT_ID_CARTOON_1_3,
	//MUSICCONTROL_EFFECT_ID_CARTOON_1_4,
	//MUSICCONTROL_EFFECT_ID_CARTOON_2_1,
	//MUSICCONTROL_EFFECT_ID_CARTOON_2_2,
	//MUSICCONTROL_EFFECT_ID_CARTOON_3_1,
	//MUSICCONTROL_EFFECT_ID_CARTOON_3_2,
	//MUSICCONTROL_EFFECT_ID_CARTOON_4_2,
	//MUSICCONTROL_EFFECT_ID_CARTOON_4_3,
	//MUSICCONTROL_EFFECT_ID_CARTOON_4_4,
	//MUSICCONTROL_EFFECT_ID_CARTOON_5_2,
	//MUSICCONTROL_EFFECT_ID_CARTOON_5_3,
	//MUSICCONTROL_EFFECT_ID_CARTOON_6_1,
	//MUSICCONTROL_EFFECT_ID_CARTOON_6_3,
	//MUSICCONTROL_EFFECT_ID_CARTOON_6_4,
	//MUSICCONTROL_EFFECT_ID_CARTOON_7_1,
	//MUSICCONTROL_EFFECT_ID_CARTOON_7_3,
	//MUSICCONTROL_EFFECT_ID_CARTOON_7_5,
	MUSICCONTROL_EFFECT_ID_COUNT,
};



class MusicControl
{
public:
	MusicControl(bool _isBackGround, bool _isEffect);
	~MusicControl(void);

	unsigned int effectId[MUSICCONTROL_EFFECT_ID_COUNT];
	//int effectId[MUSICCONTROL_EFFECT_ID_COUNT];

	void setBackGround(bool _b);
	void setEffect(bool _b);
	void recoverBackgroundMusic(void);
	void recoverEffects(void);

	void playOtherBackGround(void);
	void playGameBackGround(int _mapId);

	void playEffect(int _effectId);
	void stopEffect(int _effectId);

	void stopLoopEffect(void);
	void pauseLoopEffect(void);
	void recoverLoopEffect(void);

	void setBackgroundMusicVolume(bool _b);
	void setEffectsVolume(bool _b);
	void resumeVoice(void);
	void setIsCanResume(bool _b);
private:
	bool isCanResume;
	bool isPlatformMusicEnabled;
	bool isBackGround;
	bool isEffect;
	bool lastIsBackGround;
	bool lastIsEffect;

	int lastBackGround;

	float beforeMusicVolume;
	float beforeEffectVolume;
};


#endif

